name: VARTEST

on:
  push:
    branches:
      - '**'
      - '!master'
  workflow_dispatch:

permissions:
      actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Get Previous Run ID
        id: get_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetches the ID of the last completed run for the current workflow
          PREVIOUS_RUN_ID=$(gh run list --workflow "${{ github.workflow }}" \
          --status success \
          --limit 1 \
          --json databaseId \
          --jq '.[0].databaseId')
          echo "previous_run_id=$PREVIOUS_RUN_ID" >> "$GITHUB_OUTPUT"
      - name: Test previous run id
        run: echo "${{ steps.get_id.outputs.previous_run_id }}"
      - name: Download test artifact
        uses: actions/download-artifact@v8
        with:
          skip-decompress: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get_id.outputs.previous_run_id }}
        continue-on-error: true
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display contents of downloaded artifact
        run: cat my_file.txt
        continue-on-error: true
      - name: Test write variable
        run: python ./vartest.py
      - name: Upload test artifact
        uses: actions/upload-artifact@v7
        with:
          path: my_file.txt
          retention-days: 10
          overwrite: true
          archive: false
      - name: Print current run id
        run: "echo ${{ github.run_id }}"

